# Generated by Django 4.0.6 on 2023-11-29 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('motivo_devolucao', models.TextField(blank=True, null=True)),
                ('tipo_projeto', models.IntegerField(choices=[('1', 'EFG'), ('2', 'COTEC'), ('3', 'CETT'), ('4', 'BASILEU')])),
                ('autor', models.TextField()),
                ('data_solicitacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('prazo_entrega', models.DateField()),
                ('briefing', models.TextField()),
                ('arquivos', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[('1', 'EM ANÁLISE'), ('2', 'EM PRODUÇÃO'), ('3', 'CONCLUÍDA'), ('4', 'DEVOLVIDA'), ('5', 'CANCELADA')])),
            ],
            options={
                'db_table': 'solicitacoes',
            },
        ),
    ]
