# Generated by Django 4.0.6 on 2023-11-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0002_alter_solicitacoes_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacoes',
            name='arquivos',
        ),
    ]
