# Generated by Django 4.0.6 on 2023-12-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0003_remove_solicitacoes_arquivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacoes',
            name='status',
            field=models.IntegerField(choices=[(1, 'EM ANÁLISE'), (2, 'EM PRODUÇÃO'), (3, 'CONCLUÍDA'), (4, 'DEVOLVIDA'), (5, 'CANCELADA')]),
        ),
        migrations.AlterField(
            model_name='solicitacoes',
            name='tipo_projeto',
            field=models.IntegerField(choices=[(1, 'EFG'), (2, 'COTEC'), (3, 'CETT'), (4, 'BASILEU')]),
        ),
    ]
