# Generated by Django 4.0.6 on 2023-12-05 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitacoes', '0004_alter_solicitacoes_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pecas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.solicitacoes')),
            ],
            options={
                'db_table': 'pecas',
            },
        ),
        migrations.CreateModel(
            name='Demandas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_designacao', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status', models.IntegerField(choices=[(1, 'A Fazer'), (2, 'Em Progresso'), (3, 'Em Revisão'), (4, 'Concluído')])),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designante', to=settings.AUTH_USER_MODEL)),
                ('designante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.pecas')),
            ],
            options={
                'db_table': 'demandas',
            },
        ),
    ]
