# Generated by Django 4.0.6 on 2023-12-07 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitacoes', '0005_pecas_demandas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_designacao', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('lado', models.IntegerField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.solicitacoes')),
            ],
            options={
                'db_table': 'timeline',
            },
        ),
    ]
