# Generated by Django 4.0.6 on 2023-12-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0007_rename_data_designacao_timeline_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandas',
            name='prioridade',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Urgente')], default=1),
        ),
    ]
