# Generated by Django 4.0.6 on 2023-12-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0008_demandas_prioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandas',
            name='descricao_entrega',
            field=models.TextField(default='Nenhuma Descrição de Entrega'),
        ),
    ]
