# Generated by Django 4.0.6 on 2023-12-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0010_solicitacoes_prioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandas',
            name='devolutiva',
            field=models.TextField(default=''),
        ),
    ]
