# Generated by Django 4.0.6 on 2024-01-18 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0011_demandas_devolutiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandas',
            name='status',
            field=models.IntegerField(choices=[(1, 'A Fazer'), (2, 'Em Progresso'), (3, 'Em Revisão'), (4, 'Em Análise'), (5, 'Concluído')]),
        ),
        migrations.AlterField(
            model_name='solicitacoes',
            name='status',
            field=models.IntegerField(choices=[(1, 'EM ANÁLISE'), (2, 'EM PRODUÇÃO'), (3, 'AGUARDANDO ENTREGAS'), (4, 'DEVOLVIDA'), (5, 'CANCELADA'), (6, 'ENTREGUE')]),
        ),
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.demandas')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.solicitacoes')),
            ],
            options={
                'db_table': 'entregas',
            },
        ),
    ]
