# Generated by Django 4.0.6 on 2024-02-19 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0012_alter_demandas_status_alter_solicitacoes_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandas',
            name='data_entrega',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='demandas',
            name='status',
            field=models.IntegerField(choices=[(1, 'A Fazer'), (2, 'Em Progresso'), (3, 'Em Revisão'), (4, 'Em Análise'), (5, 'Concluído'), (6, 'Entregue')]),
        ),
        migrations.AlterField(
            model_name='solicitacoes',
            name='status',
            field=models.IntegerField(choices=[(1, 'EM ANÁLISE'), (2, 'EM PRODUÇÃO'), (3, 'AGUARDANDO ENTREGAS'), (4, 'DEVOLVIDA'), (5, 'CANCELADA'), (6, 'ENTREGAS REALIZADAS')]),
        ),
    ]
